// <auto-generated />
using System;
using FlightAggregatorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightAggregatorAPI.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20240725065417_updated")]
    partial class updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightAggregatorAPI.Models.FlightInfo", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stops")
                        .HasColumnType("int");

                    b.HasKey("FlightNumber");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightNumber = "MF123",
                            Airline = "MockAirline1",
                            ArrivalTime = new DateTime(2024, 7, 25, 17, 54, 17, 51, DateTimeKind.Local).AddTicks(4429),
                            DepartureTime = new DateTime(2024, 7, 25, 14, 54, 17, 51, DateTimeKind.Local).AddTicks(4381),
                            Price = 100m,
                            Stops = 0
                        },
                        new
                        {
                            FlightNumber = "MF100",
                            Airline = "AirBus",
                            ArrivalTime = new DateTime(2024, 7, 25, 23, 54, 17, 51, DateTimeKind.Local).AddTicks(4440),
                            DepartureTime = new DateTime(2024, 7, 25, 18, 54, 17, 51, DateTimeKind.Local).AddTicks(4439),
                            Price = 300m,
                            Stops = 1
                        },
                        new
                        {
                            FlightNumber = "FF100",
                            Airline = "Boing777",
                            ArrivalTime = new DateTime(2024, 7, 25, 16, 54, 17, 51, DateTimeKind.Local).AddTicks(4444),
                            DepartureTime = new DateTime(2024, 7, 25, 12, 54, 17, 51, DateTimeKind.Local).AddTicks(4443),
                            Price = 150m,
                            Stops = 0
                        },
                        new
                        {
                            FlightNumber = "MD101",
                            Airline = "FlightPop",
                            ArrivalTime = new DateTime(2024, 7, 26, 4, 54, 17, 51, DateTimeKind.Local).AddTicks(4447),
                            DepartureTime = new DateTime(2024, 7, 25, 16, 54, 17, 51, DateTimeKind.Local).AddTicks(4446),
                            Price = 500m,
                            Stops = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
